import { motion } from 'framer-motion';
import '../styles/About.scss';

export default function About() {
  return (
    <section className="about" id="about">
      <motion.div
        className="container"
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1, ease: 'easeOut' }}
        viewport={{ once: true, amount: 0.3 }}
      >
        <h2>About the Project</h2>
        <p>
          <strong>InCCsight</strong> is an open-source desktop software that enables processing,
          exploration, and visualization of <em>Diffusion Tensor Imaging</em> (DTI) data for analysis of the 
          <strong> Corpus Callosum (CC)</strong>. Portable and interactive, InCCsight offers advanced features
          for CC analysis at both individual and group levels.
        </p>
        <p>
          The tool incorporates three different segmentation techniques and five parcelation techniques,
          allowing comparison of data generated by different methods. A highlight is the volumetric
          segmentation method based on Convolutional Neural Networks (<strong>CNN</strong>), providing an
          advanced and effective approach for Corpus Callosum segmentation.
        </p>
        <p>
          Additionally, the software enables 3D visualization of the Corpus Callosum, adding a fundamental
          visual dimension to the analysis process. As an open-source solution, InCCsight is an accessible
          tool for the scientific and research community, promoting collaboration and advancement of knowledge
          in the field of DTI analysis of the Corpus Callosum.
        </p>
        <p>
          With a user-friendly interface and sophisticated features, <strong>InCCsight</strong> is a powerful
          choice for DTI data analysis related to the Corpus Callosum.
        </p>
      </motion.div>
    </section>
  );
}
